# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:v2x00aZ+myZYg3XAiHDcj7/MEpRid4yoqEriWQHA+zbdb3ZDHpkBJg==,iv:roDqtrktnCnn/lr94nZtKhhjXrDINslaSjtQ3074wGo=,tag:KYcOhDDa9N2syLqmVHyvlQ==,type:str]
sops:
  age:
    - recipient: age1ztnv4lsdgrdzm7wnacd2japahyhvfuxq2fhtpq0g32kghg68salqte4gkd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4S3duVnlEQTJEZFJ5Vm15
        K1ZNSGxtZ1FkbEgySkpKdC9sMjZqTEpweVFjCjQ4bVAzOHJYbHZwd1A0Y2JrS1Ra
        UEZFUm10ajY3LzNkcnJ4OFF0Z2RsdTQKLS0tIFM1cUtSeHNlbFRHRElHS054UFRt
        cFROSEVCNzY3aFBwa0lrUnRDZzBGQXcKnX5gsF3c1WP80pi9VHH2atQyStFBbC2v
        DCr0VnGJ/lEADhTm5cz7ffliCTbYxiHFaA2LEffBucc71zkIE9oM6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-31T05:48:07Z"
  mac: ENC[AES256_GCM,data:pZwNgYG+LPyKG/PuQRx7p1bW69vbiULV5Ae1WRyhUj8905cXkDLhgrwIVD4a5Ji/+8IWcZGtnMAd5SJXto+XuZS3Yd5wCXP+hQ6lEtnzTO3FvAFYDISHBKdk4YtchhWKUIofcxzOPACquxG9ox+Hypuvp5T8sLQ8dbWXfmqdgro=,iv:at4vaW8sRbudf9cTSLXn2bG/IBqPyY0LwRFOGM88t50=,tag:Uz0lPmlWncCYUCSd/xWPWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
