apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:zRQjtXL/p0G2QvCVGqHTZbsDo3ohZS3JhpZjnaqSbs9BAaPIQ3VjSw==,iv:9H6opZtyRkkaAozx5be3vdtOMQeaTGMVbm8L1yGfAMI=,tag:6UZneOpwWPK/+oyd+qrUtA==,type:str]
sops:
  age:
    - recipient: age15junp5n3mp3cwtg3kwxz7azea56936aewx4uyjaqlk38dvaq6y5s5r8lr9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUm16UjRuZDRlNlc4Sm1w
        MlZQZ2NjMlByWUZlS2hkOTVMMzNXZGpKNGtNCkRzRmx0K1NiRjZoQ3FFT1Y1VTA5
        em5LN3lRT2ZVcTJRWlhSenltWDN4RlkKLS0tIHh1UGE4MzFDUmN2VjBacGkvaE8w
        M252TTJUclNaMVZzRU5IejJxVjhjUUEKmpIWk4nwG+F3XUjlp5TiHh0OD+oxSmuf
        eT7bUSpXVH+D6mwXsHXVb3Y6JoiOxRXgIfjme/ytA61Ky4BqtV8O8A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T06:11:12Z"
  mac: ENC[AES256_GCM,data:c1uCkeQb8q0Kfcs6qD8MqKlQDNOnEOdgdGS2xMDyGnDpxCiEOdOHLf+QSE6rpibew+s9H3YnjsH4M1tiu3USS9OMwcFDEga31NCIcQJChK2frEzcmozV67Mi2UO5R40WwNqAMYLklFYDkSMHVC083YhCA9mH1ZhfL1DaiiJX0Q0=,iv:kXjrIuLR+ub4GlnD0Of5hkuvBX9lIPyIqFWKDp8BjGI=,tag:u/Xlkn4IB2CZEulEh+wtpw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
