apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:MhzNjff8G2N5zEM=,iv:bxl1DRXBZgZxZyNpa6EsqMd8HZmAZHGThINoskDh7k8=,tag:BKi4N3MzQ/a3OQFW+xJi+Q==,type:str]
sops:
  age:
    - recipient: age15junp5n3mp3cwtg3kwxz7azea56936aewx4uyjaqlk38dvaq6y5s5r8lr9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UTA4bERmR2dsYjFmbHRQ
        R0hIUlB3VHBJWlFTL0FWWm9sSTNjcVYzQWlzCnBSL1VYQ2NDL3RVdlBRZ1Bla0lO
        VzVNandEUDFVREZNaGVQSFFFTlB6QVUKLS0tIEl3cDlnWEtNN0hkamp6M3hxc1NU
        MThxY0ZoQXlsMmxobXh5VjU2cUtQRVkK+3bgbWqHaymeM03tPsJ5Zwu/l4B3oNVh
        fQ5laFNNmO5buHilzTPoMLFWuW3hfbFuMG1m8zP/PrboHseFf/4rfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T06:11:12Z"
  mac: ENC[AES256_GCM,data:jdDW+9A3tVNkcUTCpZp0kAK90hGo9KvUpIz4lIfh+W/tVebOMevZ5OlNxpBzlj4sfofQ8MXKkY7eoUI9EFy4hxCYxT67/yURz++OyHSIAK7mdk3vyQz3tNLp+jpQ1CoLRZhBhosfswQMfT98wr22saAltni++GtOmN8TYpzVqy0=,iv:8jUyuOl0md4KbfMkSTI6/Ys2lpISyEYV6gcct5XO/ow=,tag:vi4JfuQ4Qkf1fChZoDl7qA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
