apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:C3q7IOs60DKr+JU2jOUB7T5Vd6LPsbpNywBNbexRNvo=,iv:hhNx86pTgsxMkjSM2rPZOyDiicYgPRDmXTeitE7paFI=,tag:AkBw+yQqlPCAfzL5mCvTYg==,type:str]
sops:
  age:
    - recipient: age15junp5n3mp3cwtg3kwxz7azea56936aewx4uyjaqlk38dvaq6y5s5r8lr9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSENEaWhuMmZwRmgxazFw
        ZlhFSGEvZWtSNEZFOXRoU0pWZGdYcUdRSVVnCmQyYkZvQlFlMXZWK3BMM1M3ekRQ
        eCtuRVE5TTFMVGpwemhqU2h5T1J3d2sKLS0tIE9xZVFzeGFPQ0kwOXR2YmNRL1py
        ZUFNZzNaVUg0REtkN01GT1ZDWURQVVUKRTG3GYYL/fZKKhPNCiHqw3VPSIHZ2aRW
        HzwaIru1rLOyHe3pKH38JE5HPIQGggW6oRiBkX1ZBuMzM0ujjjsHKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T06:11:12Z"
  mac: ENC[AES256_GCM,data:tTH9o6CiuaD4HdPoinn1I7q+oPpvljib7H0s4ZiNWy3aEt6PYC//4nDdzKeEX1A+UZrgGQbkTvluiiBh8ukkZIe3jaHtMtW4O91AZvUiAUSa1pVWotoPvDJrUoDRJWMjtE+zAlDuMvzsowB5tFymSqf6XATp5p4dL5PjhnW/QPE=,iv:Y8EDXU36HOC7Ph5NeA89feSD+wcqdJZCIv/u/eRtjG8=,tag:MpbLJqkHLNdUI3CwDYq8sw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
