# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:zCN6RUj0LIi86l/AJ4Le2JFM5qp6qFvmlJwj/tmGpdE=,iv:MYh2UO0JP2oBrNPSZm61l49N0gQm+vp3GE1x8NdH16U=,tag:i55riSKCg1XKgjcsOXodLA==,type:str]
sops:
  age:
    - recipient: age1ztnv4lsdgrdzm7wnacd2japahyhvfuxq2fhtpq0g32kghg68salqte4gkd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MWRlUFJOa3BWMEtpRHI5
        ejFmeHF0OHMrQWdRZUQzcER5cG1DcEJqYlFjCllsUytvaE1kWmFwVFFVUXBYaUpj
        MDJzdUNFUTZHY1BxZ0Y3ZlZsMys0dk0KLS0tIGFaWVBiRFZzcXJKV2ZQMThSZ2RV
        UlVhSmIrN3VacG1BeC83VHVoQStFOUUKqbB6cub9rp3lSqqabAtQSifAM9Lwy7+f
        7jYbGYm3yO7rBEn+tLfbcgwNwN7rRZ7cLLiQjmZLLrmxHNXaVQT0Xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-31T05:48:06Z"
  mac: ENC[AES256_GCM,data:sBUdJiBkQPuktwIPP+RRyOi7/g1qzH5yi+0/pcwhNOpsBOTD2zKL6JR7U60y+hyKv8kylCkt7kvr8pIoujBA7OtGdx1pPIt8tnq/wFHeQfB0lJZH1I0kABIrUzou+LFLsGTWZ12FxPIsQiiRcBBmrQpBR3nnH5IQ39x90OAf+go=,iv:yYSwjwlcGItGW1xlznuUdwQ45ygsg5CWgJ6/qOu8rCU=,tag:6pL3iPpSnu+5w4YYC5rnpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
