# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:j4NIIOM6+EQ4GiQsxk8P2uIMU2wr/+myecZHKbUfqve7x1h8UZ2mmuf0sdgBTNkFNB286rVxSaOlMKyF4p9sAd6JrAQcZBr+GNwRDcZ69ISJbA4n7dLMlZeV8NnHhKFPtCBHzlfvGlnId3+5q+l+SspRfYZGK1oHyDB1XtqRGybPPGvRcrMiLeOm+T+8htn7rZYjpS3NP1IK8q3juz4dCL9UFHFCQpvqAEE5tA5XIXVPg8ek,iv:R1o9s3U07AdzBXqvUwUkf3zMv5wNSpQ0V/sCVTRddwQ=,tag:pqpmycz4CbmNIi2I5NhvQg==,type:str]
sops:
  age:
    - recipient: age1ztnv4lsdgrdzm7wnacd2japahyhvfuxq2fhtpq0g32kghg68salqte4gkd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWndlcFZta2xKVWY5ajd4
        Z0sxc0J5OHRzeGJidWFNcUlDT2FaUDZKQ0U0Cm9ieExaVjhORUVCMVBWT0h0V0E0
        b2k2eU1EZU5YUUZFTWR1eDhRaFQzaVkKLS0tIEZLY1BYVmFxbldWbDJ6UkFRSWVp
        TFZtR1Z3eUxsSmFMWGZUUTZRUHhyblkKEt6dCWsyek7Suf1ZI9+/HtLv94VtOTAi
        h1wNuMOHiRW/cL+5tLinVASuYd1DLjJWuAUSujHDrhHLp8C8NNBZWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-31T05:48:07Z"
  mac: ENC[AES256_GCM,data:VjyoRl9Tn1nwizl1lRJnXh9jEMYcQF/PrpE99JnX6qXPzsqirzG96eKaOnfzr45w6oK7Y0e0xYuNqEjVfcnskUI2AoIyjen3G7pzOpPPKf8y8cwi18Dx9Di6PZec05Uo2T1/PZQCOxb5Ejtv3NXjjvo/Zki1ls0ki3xhb4Qm/NQ=,iv:nXrAjGf7wKrQxh1XNZNoSo2CMOjKu6IlGqMKtGAV4g4=,tag:RIXZ3csZJkd+29kcGn1+YQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
