apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:umCAjrLKEa4zjpDWywhpx+Hv+Bhq1YKY/s5gwdllsylcZ8CkxcKB9JwPn1yqqbLV0/g5kHZV8YoKoEGK0LV07vSjJnrW4vHR5yTC3B0agsy4Vfz7VRhLgRhQbVEPJxkZyTNpxk8q9oUn+gNwlwKeU0O2/NpuIzVFQzKJx5PWhRWVqhuWEd+jkaWIGj1jCfK+5c9HPHmYb4L6qunSeOF2sTvFA/Q0Dk8xWPN4VHxr9yuN/Mo1,iv:5/3Nr99zpIgsKXMUOyIdVJOSLskz4BdbHceL6gYIB+4=,tag:JoncfYF42Qa8kIve0TDxnw==,type:str]
sops:
  age:
    - recipient: age15junp5n3mp3cwtg3kwxz7azea56936aewx4uyjaqlk38dvaq6y5s5r8lr9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZGpvWkxWZjYyNWw5QjF0
        MFpqa05WenFYT3I1dFBvT1dBczJGWHJIWUhZCk1iWStNTTVMT2JNeFdhK2VrVU4x
        QzlzREp6QnpRQUF3bS83ZnFPQTVCTDgKLS0tIDg1cW1kRHhzYVN6MVByZUtzWXd4
        eGZ2TXFEcDJpMXV4UkJrcnZGRnVOd28KOYqZ+NnOrBKegZbnqnnPq9te9rSUPAZl
        0YEWrxGDi7qR4QZUP1tKKAMLCSx6JA0lmivsjV5/EfonzdIO/a75sg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T06:11:12Z"
  mac: ENC[AES256_GCM,data:3SYd+w6f0NMPX64k22UKZaDBpK2LiFe9wqAYWd+cTnlX9yh4d2bENL1q8gH5/YfTeB4iI7pa2P1pZ3elHQs9mVLRm+pYcFOONSYcDAHCnX0mLkd8FLpqFSuzr3XGgHDX1WjZtKNrS3c42hz9Bt7aYDB4EeNMiGsuaptnF+woOMo=,iv:6DfeZD59mHgPG5WOvfK0r//ZiP+3zRMtykIhDKCFqt0=,tag:zekN9mLOYHP4nweEhDKBJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
