apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0LZDirGHk2cESE+bXKmvE8/DDSYMLeUPK5LqMosLwUiMqIPJMZWUUA==,iv:Oy9Gvk+wbehvkJ1BSjB9sDpR1b4/LowI+MJjzXMFYEM=,tag:R0j3J3JZZqZT++J6zBG59Q==,type:str]
sops:
  age:
    - recipient: age15junp5n3mp3cwtg3kwxz7azea56936aewx4uyjaqlk38dvaq6y5s5r8lr9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1c1BYZFVEVVVETlg4WUt2
        ODBmWmZQTExkZEVFRWRoeEhXWWtMRlRTaERFClFEUk4yVnhzM0xSZlgyMXZGMUww
        Skh5Yk83WXQ3M04xdUMwcEhnc3B2aGsKLS0tIHdTenJ4VFZKUUJDc1hlQm1vdjUw
        VUNTUUtjR2pkQXFUYUFzMlhHQTRlZjAKJVz7Pyb/84HGJ5J45Q2Q9fvjHGlm8mXl
        YOjIoHGz+aU9PtK8miGGyRseMy7UpbaZ8nwBlHi4GY5/PH+xOdJqKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T06:11:12Z"
  mac: ENC[AES256_GCM,data:/DkWL7rfC7EYjdQ/uxpPFILA3GPSegOZlDjFKM6GA8agbB+FoLTg27fr6YgTjWgC7cs5AATTYJGQXtR3jsilwGbGTuDeGFcB4TpkQQLGGFGX4hzXcHziV5NFLKbprVVxedKzOcwieoPPASeMAvyDP2kjabHXTs2nr8xn2S/FFYo=,iv:qBAsgelyyrsIEpJmdcEzZjdJqWWk3FEFX09zpBTmeKw=,tag:Iu7VnfGE/Uw5yAu2pqgGOA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
