# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:YOWY+k9R7iaWIyFCib+g4DoQgtKiXqhp2R/K9PkpxFopcyWUoZ7drA==,iv:Px4OzKAYWf7odWjVMuAz8GI5NM93Od+b5jo3KV4De78=,tag:kWZ0jqFQ3oWtooJpt/7lxA==,type:str]
sops:
  age:
    - recipient: age1ztnv4lsdgrdzm7wnacd2japahyhvfuxq2fhtpq0g32kghg68salqte4gkd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtam80c0R3QmpUL3I4MFN6
        MFo5Yk5ZUG1lV0wvMVVEWlhyYXk1MkM4ZUYwClNpU0FKV3Bsbm15UFl0Q1k4dm5X
        U1Ava3RwRFpXa3VKVmVLa0RHb3dWMUkKLS0tIFJ0N01XM01tV0tFOHNGR0h0Y1R4
        L2QyVk52UVlPUXFLd0ozU2VVNjU4SmMKTHTkQzUmE9Ik7k+yfS4C6jp39XTN294P
        A1v8IyjorFnDfUx8lpZHDLntjmWGoIWNidZ5z0pbBMye9TCXYb+Trw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-31T05:48:06Z"
  mac: ENC[AES256_GCM,data:PgfTt90N3+46KRZFeXZpnlwlFXwtSnBRbh56nlFJ8gZ/c9gD2TtqpP1WZxWwwJ4eskUJH8Z99wPptE7da9NF6hAAMaH2IJ/V8mmckPOQ1oA7NEFyEemiqhRrSK+Uu/4fU6r95QGvg6NTowQybUEkDh7xSNE8VhlcE1Fq49Y1viw=,iv:Tyru1L67zaPuZjaiJvCtupOS9L1E4mPRnK0swvEFklg=,tag:fALXnWOud6AnNnfVrMKhig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
